### ISSUE TITLE
Benefits of this api against kleiram/transmission-php

### ISSUE THREAD

**Issue by popstas** [MartialGeek/transmission-api#1]
Hello, I need for transmission api for automate my transmission. Yesterday I found most popular [kleiram/transmission-php](https://github.com/kleiram/transmission-php). Today I found your api and want to use it.

Can you explain your api benefits? I quickly compared two libraries and found that you have:
- move / rename (transmission-php have unmerged PR)
- queue priority
- full rpc-spec implementation
- better test coverage

On another side, transmission-php have:
- more simple usage case (class Transmission, torrent model)
- potentially more of stability (but you have tests)

Maybe would be better to add class that will hide session id providing from api user?

**Comment by popstas** [comment]
@kleiram, what you think about this api?

**Comment by kleiram** [comment]
I think this is a perfectly fine API as well. I think it depends on preferences, my API is indeed kind of outdated and I don't have a lot of time for PR's unfortunately :(

The main difference I see is that this is a basic RPC client (there's nothing wrong with that though) while my library tries to wrap the API in a sort of repository pattern. If you don't need any fancy models or anything like that, and you need some features that are not supported in my client, I'd so go ahead and use this one, since it looks fine to me! :)

**Comment by MartialGeek** [comment]
Hello

I'm sorry, I have a problem with the github notifications!
I don't remember if I already used this library. The only thing I can say is that all the libraries I've found did not implement the full RPC API. So I decided to create my own.

About the stability, I work in TDD. It doesn't mean that I can introduce bugs, but the risk is decreased.
About bugs, I have to fix one with a the new logger feature :p
I will work on this issue after my working day.

**Comment by popstas** [comment]
You can click "Watch" on top of this page to enable notifications.

I think that your library should have wrapper class with most used RPC tasks. As kleiram said, wrapper is main benefit of her library against your library. Users can use wrapper for main functional and direct $api requests for other. And implementing wrapper functions is more simple task that implementing missing RPC functional. Therefore I decided to use your library in my project [popstas/transmission-cli](https://github.com/popstas/transmission-cli).

I almost have not experience with frameworks, TDD and DI, but I wrote [TransmissionClient.php](https://github.com/popstas/transmission-cli/blob/master/src/TransmissionClient.php) wrapper in my project.

Hou do you use your library?

**Comment by MartialGeek** [comment]
This library is just a PHP implementation of the Transmission RPC API. I don't want to add any business logic. It has a single responsibility, communicate with Transmission. This is a technical, low-level component.

Currently, I don't use my library yet. I created it because I'm writing an application for a seedbox, and I need a full Transmission RPC client. The code that will be responsible of the torrent data model will use the library like a database, in a higher abstraction level.

**Comment by popstas** [comment]
Thanks!
